export const USERREGISTERREQUEST = "USERREGISTERREQUEST"
export const USERREGISTERSUCCESS = "USERREGISTERSUCCESS"
export const USERREGISTERFALIURE = "USERREGISTERFALIURE"
export const USERLOGINSUCCESS = "USERLOGINSUCCESS"